### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by jessicafarias**
Added all the elements and style for the website.

#HEADER
- The header contains a background-image
- Navbar: inside the header, it contains different links and inside that links are span tags
- The header contains some text and occupies most of the website

#MAIN (Images-section)
-I consider this section as the main, and the main contains 4 different images of apple promotions

#FOOTER
-The footer contains 2 divisions with the same width. I implement Flexbox to make it responsive

Comments:
-I obtain a similar effect for the input text using focus and transition and Flex for the nav-bar to move all elements inside.
-The website is validated with Linter and W3 Validator.
-I try to order all for each element in the next order: Positioning, Box model, Typographic, and Miscellaneous.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @krash46, congratulations on a great job done :+1: PR has a title and a description, README  looks professional :smile: Overall the project looks great. However, there are a few changes we need to implement. Kindly address the comments below:
- Let us apply the DRY rule to our CSS code. This [article](https://speckyboy.com/good-bad-css-practices/) would be helpful
- Kindly add a link to the copyright
cpp
- Kindly use the CSS float property along with either flex or grid
cpp1
- Kindly add how to clone the project in the README file


Kindly make these changes and submit another code review :slightly_smiling_face: 
_Happy coding_ :woman_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo)

**Comment by jessicafarias** [comment]
Thanks a lot to help me to improve my skills on HTML and CSS
Changes:
-I implement float to positioning the footer links
-I modified the README file with instruction on how to clone the project
-I use validator w3 to check HTML file
-I delete not necessary classes on CSS and HTML
-I use Mort to verify do not have "death" classes in CSS file
-I use linter and stickler to validate CSS file
-I verify to have all links as the original website

**Review by lucasmazo32 — APPROVED** [review]
# Project approved :rocket:

#### Great job!

#### Your project looks great!

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

**Pull request merged**
